apiVersion: apps/v1
kind: Deployment
metadata:
  name: digital-key
spec:
  selector:
    matchLabels:
      app: digital-key
  template:
    metadata:
      labels:
        app: digital-key
    spec:
      containers:
        - name: digital-key
          image: jongwon254/digital-key:latest
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080